/**
 * Calendar event types
 */
export enum CalendarEventType {
  WEEKLY_CALL = 'WEEKLY_CALL',
  PROJECT_REVIEW = 'PROJECT_REVIEW',
  MENTORSHIP_SESSION = 'MENTORSHIP_SESSION',
  MENTOR_1V1 = 'MENTOR_1V1',
  COMMUNITY_MEETING = 'COMMUNITY_MEETING',
  SPECIAL_EVENT = 'SPECIAL_EVENT',
}
